// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Console log laga kar check karein ke URL mil raha hai ya nahi
console.log("Connecting to:", process.env.DATABASE_URL);

export default defineConfig({
  schema: "prisma/schema.prisma",
  // URL ko direct process.env se dein
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
